### ISSUE TITLE
Error loading library

### ISSUE THREAD

**Issue by hwells1** [iamaziz/ar_wordcloud#3]
Hi,

Thanks for providing the library.

I have successfully installed the package using `pip install ar_wordcloud` but I am having an issue loading the library. I run the code below and get the error message. 

`from ar_wordcloud import ArabicWordCloud`

`UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 75: character maps to <undefined>`

Perhaps it is something simple I have overlooked, but I cannot find any solutions. Do you know a fix?

**Comment by iamaziz** [comment]
Hey there, thanks for reporting this issue.

It seems you're on a Windows machine (unfortunately, I don't have Windows to test this). But this might be [some encoding](https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character) issue when opening the stopwords file. Can you find [this line in](https://github.com/iamaziz/ar_wordcloud/blob/master/ar_wordcloud/ar_wordcloud.py#L17) in your installed package files? If so, pls try to modify the file and change that line to:

```python
STOPWORDS = set(map(str.strip, open(os.path.join(THIS_DIR, "stopwords"), encoding="utf8").readlines()))
```

Pls let me know if that solves your issue. Thanks.

**Comment by hwells1** [comment]
That worked, thanks!
